version: '3.9'

services:
    client:
        build: ./client
        ports:
            - '5173:5173'
        volumes:
            - /app/node_modules
            - ./client:/app

    # server:
    #     build: ./server
    #     ports:
    #         - '5000:5000'
